default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] %>
  username: <%= ENV["USER"] %>

development:
  <<: *default
  database: sso_rhomobile_development

test:
  <<: *default
  database: sso_rhomobile_test